### ISSUE TITLE
Update URL for documentation

### ISSUE THREAD

**Issue by stefsmeets** [FormingWorlds/PROTEUS#122]
Seems like readthedocs does not approve of updating the url: https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-my-project-slug-the-url-your-docs-are-served-at

_Originally posted by @stefsmeets in https://github.com/FormingWorlds/PROTEUS/issues/121#issuecomment-2269224748_

We could try to set up a new project under the new URL and use that instead. [readthedocs](https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-my-project-slug-the-url-your-docs-are-served-at) does not support changing the url through their backend.

**Comment by timlichtenberg** [comment]
Good for me, homogenising both URLs and the look and feel of the docs is of high priority I think.

**Comment by lsoucasse** [comment]
Agreed.

**Comment by stefsmeets** [comment]
Sounds good, I will also see how we can set up subpages for the different projects we have atm (janus, mors, any others?).

**Comment by stefsmeets** [comment]
I have created a new project under the name `fwl-proteus`: https://fwl-proteus.readthedocs.io/en/latest/

### TODO
- [ ] Set up github integration
- [ ] Set up subprojects
- [ ] Change references in documentation

**Comment by stefsmeets** [comment]
@timlichtenberg Could you give me maintainer access so that I can set up the readthedocs integration (so that it automatically builds on every push)? I don't have the permissions.

**Comment by timlichtenberg** [comment]
I used this request to unify access rights. @stefsmeets @lsoucasse @nichollsh you should have now unified "maintain" rights on all PROTEUS repositories (at the moment PROTEUS, JANUS, MORS, ZEPHYRUS, SOCRATES) through the "PROTEUS maintainer" team. Please let me know if you encounter issues

**Comment by nichollsh** [comment]
Thanks, Tim!

**Comment by stefsmeets** [comment]
Thanks @timlichtenberg! Could you check if you can give us access to webhooks?

https://docs.readthedocs.io/en/latest/guides/setup/git-repo-manual.html#manual-integration-setup

**Comment by stefsmeets** [comment]
I believe so, usually it is automatic if you have the rights when you import the project on readthedocs. Feel free to have a go yourself: https://readthedocs.org/dashboard/fwl-proteus/integrations/275696/

The steps are described here: https://docs.readthedocs.io/en/latest/guides/setup/git-repo-manual.html#manual-integration-setup

**Comment by timlichtenberg** [comment]
I will not be able to do this today or potentially until next week, apologies. To not be the bottleneck, I just gave you temporary admin rights, if that's fine for you. :>

**Comment by stefsmeets** [comment]
Everything working as expected, I'm closing this issue.
