### ISSUE TITLE
Aragog submodule

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/PROTEUS#236]
We now have a basic version of Aragog implemented within Proteus. This issue lists the next step towards an actual replacement of C-Spider.

- [ ] Debug coupled interactions as it seems to misbehave, see [here](https://github.com/FormingWorlds/PROTEUS/issues/62#issuecomment-2431755202). We could also compare Spider and Aragog on a single run to gain insight on what is going on here @planetmariana.
- [ ] Write plotting routine to get similar output as Spider
- [ ] Use look up tables for thermophysics properties downloaded from the OSF ExPlanetology/aragog#7
- [ ] Introduce core cooling boundary condition ExPlanetology/aragog#8 
- [ ] Set up an integration test with core modules (Janus/Mors/Zephyrus/Caliope/Aragog)

**Comment by lsoucasse** [comment]
Also I realize I did not implement the "attempt" loop as in spider, where tolerance/dt is adjusted when solver fails. Maybe it can help.

**Comment by nichollsh** [comment]
I have made some progress on the second point. See the plot below. We can think about merging these changes into aragog and PROTEUS once the current aragog-related PR is merged.

<img width="1120" alt="image" src="https://github.com/user-attachments/assets/6449b8cf-8f79-4830-adfb-28c78507b0d6">
